# Generated by Django 4.2.7 on 2023-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="po_number",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
